baseURL = "https://haivle.com/"
#baseURL = "https://randomwalk94.github.io/refined/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "A Random Blog"
googleAnalytics = "UA-114685053-3"
theme = ["hugo-debugprint", "hugo-jf2",   "hugo-atom-feed", "hugo-search-fuse-js", "refined"]


contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

pygmentsCodeFences = true       # This applies to Chroma too.
# Use pygmentize generated CSS file instead of inlining the code codes in the HTML.
# See https://gohugo.io/tools/syntax-highlighting/#pygments and
# https://github.com/richleland/pygments-css
pygmentsUseClasses = true       # This applies to Chroma too.
pygmentsUseClassic = false


# Default values of custom site.Params
[Params]
  tagline = "Just want to write stuff"
  mainSections = ["posts", "notes"]

  # https://github.com/tummychow/lanyon-hugo/issues/2#issuecomment-253274278
  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  themecolorbase = "red" # Valid values: "red", "orange", "yellow", "green", "cyan", "blue", "magenta", "brown"

  # Set favicons to true only if the following files are present in the project assets/ dir:
  # - safari-pinned-tab.svg
  # - manifest.json
  # - favicon-16x16.png
  # - favicon-32x32.png
  # - apple-touch-icon.png
  favicons = false

  # These inline CSS files have to live in layouts/partials/.
  custom_inline_css = [ # Pygments Trac theme
                        # "css/trac_pygments.css"  # Needs pygmentsUseClasses to be true
                        # Chroma Trac theme
                        # "css/trac_chroma.css"    # Needs pygmentsUseClasses to be true
                        # Chroma GitHub theme
                        "css/github_chroma.css"    # Needs pygmentsUseClasses to be true
                        , "css/style.css"
                      ]

  css_lazy_load = false

  [Params.fontawesome]
    style = "fal" # Valid values: "fas" (Solid), "far" (Regular), "fal" (Light), "fab" (Brands)

  [Params.urls]
    refined = "https://gitlab.com/kaushalmodi/hugo-theme-refined"
    ox_hugo = "https://github.com/kaushalmodi/ox-hugo"
    hugo = "https://github.com/gohugoio/hugo"
[Taxonomies] # [indexes] is obsolete since v0.11
  category = "categories" # SINGULAR = "PLURAL"
  tag = "tags"
  series = "series"


#[outputs]
  #home = ["HTML", "RSS", "ATOM", "JF2Feed"] # default = ["HTML", "RSS"]
  #section = ["HTML", "RSS", "ATOM", "JF2Feed"] # posts/atom.xml
  #taxonomy = ["HTML", "RSS", "ATOM", "JF2Feed"] # tags/foo/atom.xml
  ## Fri Mar 23 17:57:08 EDT 2018 - kmodi
  ## There's some issue on Hugo 0.38-DEV (older versions too)..  The "ATOM"
  ## output format is not getting generated for taxonomyTerm.
  ## taxonomyTerm = ["HTML", "RSS", "ATOM", "JF2Feed"]
  #taxonomyTerm = ["HTML"] # tags/atom.xml
  #page = ["HTML", "JF2Post"]

  [outputs]
    home = ["HTML"] # default = ["HTML", "RSS"]
    section = ["HTML"] # posts/atom.xml
    taxonomy = ["HTML"] # tags/foo/atom.xml
    # Fri Mar 23 17:57:08 EDT 2018 - kmodi
    # There's some issue on Hugo 0.38-DEV (older versions too)..  The "ATOM"
    # output format is not getting generated for taxonomyTerm.
    # taxonomyTerm = ["HTML", "RSS", "ATOM", "JF2Feed"]
    taxonomyTerm = ["HTML"] # tags/atom.xml
    page = ["HTML"]
#  [[Params.social]]
    #name = "Github"
    #link = "https://github.com/kaushalmodi/"
    #relme = true
  #[[Params.social]]
    #name = "Gitlab"
    #link = "https://gitlab.com/users/kaushalmodi/projects"
  #[[Params.social]]
    #name = "Hacker News"
    #link = "https://news.ycombinator.com/user?id=kaushalmodi"
    #icon = "hacker-news"
  #[[Params.social]]
    #name = "Twitter"
    #link = "https://twitter.com/kaushalmodi/"
  #[[Params.social]]
    #name = "Mastodon"
    #link = "https://mastodon.technology/@kaushalmodi"
    #relme = true
  #[[Params.social]]
    #name = "Keybase.io"
    #link = "https://keybase.io/kaushalmodi"
    #icon = "keybase"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true


  # [Params.prefetch]
  #   fonts = ["/fonts/libre-baskerville/2012/subset/LibreBaskerville-Regular.woff2",
  #            "/fonts/iosevka/1.14.1/subset/iosevka-ss08-regular.woff2",
  #            "/fonts/linux-libertine/5.3.0/subset/LinBiolinum_Rah.woff2",
  #            "/fonts/source-sans-pro/2.020R-ro-1.075R-it/subset/SourceSansPro-Regular.woff2"]
